improve ./release, add .releaseignore

diff --git a/release b/release
--- a/release
+++ b/release
@@ -8,7 +8,11 @@ main() {
 		die 'Usage: ./release [-h|--help|-n|--major|--minor|--patch|<version>]'
 	fi
 
-	test $# -eq 1 -a "$1" = '-n' && shift || local test='--test'
+	if test $# -eq 1 -a "$1" = '-n'; then
+		shift
+	else
+		local test='--test'
+	fi
 	./build $test   || die 'Please fix the build first, then try again'
 
 	if test $# -eq 0; then
@@ -26,6 +30,7 @@ main() {
 			git commit -m "Release $version"        || die 'Failed'
 		fi
 		git tag -a -m release "$version"                || die 'Failed'
+		# git push --follow-tags                          || die 'Failed'
 	fi
 }
 
@@ -37,10 +42,14 @@ release_project() {
 	else
 		prev_version=$(list_versions | tail -n 1)
 	fi
-	git diff --binary "$prev_version" | perl -0777 -pe '
-		my $skip = qr{\.gitignore|build|release|deploy|migrate|(.*/)?\.release/.*}ms;
-		s{^diff --git a/($skip) b/\1\n(?:(?!diff)[^\n]*\n)*}{}msg;
-		' > .release/$(< VERSION).patch
+	git diff --name-only --binary "$prev_version" |
+                perl -MPath::Tiny -ne '
+                BEGIN { $skip = join q{|}, map { s/\A\s+//; s/\s+\z//; qr/$_/ms }
+                                grep { !/\A\s*(?:#.*)?\z/ms } split "\n",
+                                path(".releaseignore")->slurp_utf8 }
+                chomp;
+                print "$_\0" if !/\A(?:$skip)\z/ms;
+                ' | xargs -0 -r git diff --binary "$prev_version" -- > .release/$(< VERSION).patch
 	test -s .release/$(< VERSION).patch || rm .release/$(< VERSION).patch
 }
 
