[narada-base] change release tag's message

diff --git a/release b/release
--- a/release
+++ b/release
@@ -24,7 +24,7 @@ main() {
 			git add ".release/${version}".*         || die 'Failed'
 			git commit -m "Release $version"        || die 'Failed'
 		fi
-		git tag -a -m "$version" "$version"             || die 'Failed'
+		git tag -a -m release "$version"                || die 'Failed'
 	fi
 }
 
